### ISSUE TITLE
I was noticing huge bundle sizes for my app until I used --experimental-scope-hoisting

### ISSUE THREAD

**Issue by wcjr** [DeMoorJasper/parcel-plugin-svelte#131]
# 🙋 Feature Request

I'm hoping a reference could be made somewhere in the docs to the possibility of seeing larger bundle sizes than one might've noticed using a rollup config.  Or I suppose there's a possibility @DeMoorJasper  might know why bundle sizes might be getting larger with a parcel approach than the rollup approach.  Either way, I'm grateful for this plugin and expect more and more people will start using it as Svelte gets more popular.

## Detailed description

My prod bundles were nearly 3X the size using parcel (and this plugin) than they were when I was used rollup.

## Similar to an existing solution?

I could not find the right combinations of configs to get my bundles sizes small again.

## Possible work-around?

I came across the `--experimental-scope-hoisting` flag in parcel's docs and it drastically reduced by bundle sizes again and my app still worked!

## Related to a problem?

I assume is has something do with svelte things not getting de-duped or something but did not dig into it very far.

**Comment by wcjr** [comment]
I'm working in https://github.com/silinternational/wecarry-ui/tree/move-to-parcel if anyone is interested in the build config.

**Comment by DeMoorJasper** [comment]
Scope Hoisting should fix this slightly but 3x smaller bundles seems a bit extreme. Maybe something's done wrong in this plugin, Svelte or in your codebase that relies too heavily on scope hoisting.

If scope-hoisting fixes it that's the way to do it, as that;s the default in rollup

**Comment by wcjr** [comment]
**For reference**

with `--experimental-scope-hoisting`:

```
npm run build

> parcel build src/index.html -d public --experimental-scope-hoisting

✨  Built in 18.51s.

public/main.aefbfc94.js       353.88 KB    17.50s
public/main.645e4805.css      159.84 KB    16.19s
public/index.html                 517 B     6.20s
public/global.6f8fb1a8.css        483 B     6.77s
```

without `--experimental-scope-hoisting`:
```
npm run build

> parcel build src/index.html -d public

✨  Built in 15.51s.

public/main.eeb87dd0.js.map       ⚠️  2.96 MB     207ms
public/main.eeb87dd0.js           ⚠️  1.26 MB    14.29s
public/main.cbb1d593.css.map       265.14 KB      33ms
public/main.cbb1d593.css           159.88 KB    12.66s
public/global.49fcf85e.css.map       1.11 KB       5ms
public/global.49fcf85e.css             532 B     1.71s
public/index.html                      517 B     956ms
```

I'm not sure where the culprit is but if there's something obvious you see in our project that's not being done correctly, I'd appreciate the feedback, thank you!

**Comment by DeMoorJasper** [comment]
@wcjr I guess svelte relies on scop-hoisting pretty heavily, can't seem to think of any other reason based on your code. Scope-hoisting is just another form of minification that's why it's smaller it's just a surprisingly big difference but as long as the code works it should be fine. Svelte is probably also built to utilise scope-hoisting to it's full extend. (as rollup which kind of invented scope-hoisting and svelte are built by the same person)

Scope Hoisting is currently experimental so be careful when using it, but it will become stable in Parcel 2, so it should be safe to use at that point.

Rollup has treeshaking (scope-hoisting) enabled by default, it was also the big shiny thing that differentiated Rollup from everything else at the beginning if I'm not mistaken.

Hopefully this helps you out with your concern about bundle size. There's nothing else I can really do here

**Comment by wcjr** [comment]
Thanks, yeah Rich would know best how to utilize the two together for sure!  I'm thinking some mention of this possible issue with bundles sizes might be valuable in the docs...it would've helped me, I feel like I got sort of lucky to stumble across the flag.

**Comment by DeMoorJasper** [comment]
It should probably be here: https://parceljs.org/production.html#optimisations but it's experimental so we didn't really wanna push people to using it yet. We'll definitely push people to use it in Parcel 2, as it will be opt out.

The docs for that will be out soonish
