### ISSUE TITLE
Root component gets duplicated when index.js is saved

### ISSUE THREAD

**Issue by EmilTholin** [DeMoorJasper/parcel-plugin-svelte#31]
# 🐛 Bug Report
The root component gets duplicated when the file where the component is created is saved.

![duplicate_component](https://user-images.githubusercontent.com/11573167/47504974-82a9c880-d86d-11e8-860a-6b0ae29c42a0.gif)

## 🎛 Configuration (.svelterc, package.json, cli command)
Parcel with the `parcel-plugin-svelte` plugin.

```json
{
  "scripts": {
    "start": "parcel ./src/index.html"
  },
  "devDependencies": {
    "parcel-bundler": "^1.10.3",
    "parcel-plugin-svelte": "^1.2.3"
  },
  "dependencies": {
    "svelte": "^2.14.3"
  }
}
```

## 💻 Code Sample
Open the [minimal reproducible example](https://github.com/EmilTholin/parcel-plugin-svelte-test), run the outlined commands in the README, and save the `src/index.js` file.

**Comment by DeMoorJasper** [comment]
That kinda makes sense as parcel's hmr just executes the piece of code that got saved. Which is what HMR is.

Pretty sure Svelte has something to prevent this.

cc @ekhaled (Perhaps you know how to fix this, as you commited the HMR functionality)

**Comment by ekhaled** [comment]
IMHO it's not a `parcel-plugin-svelte` bug.

Svelte's HMR is constrained to svelte components.
It knows how to hot-reload a component only.

If you changed `App.svelte` it works as expected. Because `App.svelte` knows how to handle itself when a hot reload comes in (thanks to `parcel-plugin-svelte`).

`index.js` on the other hand:
 a) is not a svelte component
 b) does not go through `parcel-plugin-svelte`

If you need `index.js` to hot-reload.. you will need to shoe-horn custom code to handle reloads. maybe something like:
```js
import App from './App.svelte';

var app = new App({
  target: document.getElementById('root')
});

if(module.hot){
  app.destroy(true);
  document.getElementById('root').innerHTML = '';
  new App({
    target: document.getElementById('root')
  });
}
```

Not saying the above will work.. just trying to demonstrate how it needs to be responsible for its own cleanup and re-render.

**Comment by EmilTholin** [comment]
Yes, you're right. It's just something you have to keep in mind when using HMR, I suppose. Thank you both for your time.
