### ISSUE TITLE
Symbols "<" and ">" in html content return "Expected valid tag name"

### ISSUE THREAD

**Issue by Asrover** [DeMoorJasper/parcel-plugin-svelte#65]
# 🐛 Bug Report

## 🎛 Configuration

```
{
  "name": "svelte-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "svelte": "^3.6.1"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.3",
    "parcel-plugin-svelte": "^3.0.1"
  }
}
```
Command: parcel watch index.js

## 💻 Code Sample

```
<div class="left-control"> < </div>
<div class="right-control"> > </div>
```

## 🌍 Your Environment

Svelte 3.6.1, Parcel 1.12.3

**Comment by orlov-vo** [comment]
`svelte/compiler` can't to build AST from your code. If you want use this symbols use html escaped equalient:

```html
<div class="left-control"> &lt; </div>
<div class="right-control"> &gt; </div>
```

**Comment by Asrover** [comment]
Thank you, my mistake.

**Comment by Slowwie** [comment]
But what if the values comes from my api and the user inserted it. I can not want my users to use &lt;, and &gt; for every text input. Is there a solution for this?

**Comment by antony** [comment]
@Slowwie you absolutely under all conditions need to sanitise html that is provided by your users. This isn't specific to parcel or svelte, it's a critically important rule for any website.

When a user adds html to your site, and you expect to render that html later, you need to parse, remove script tags, fix broken html, and escape special characters. Otherwise you are opening up your users to a huge amount of security issues.
